import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EnvSync from "../components/EnvSync";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <EnvSync env={{
          NEXT_PUBLIC_AUTH_URL: process.env.NEXT_PUBLIC_AUTH_URL || '',
          NEXT_PUBLIC_USER_URL: process.env.NEXT_PUBLIC_USER_URL || '',
          NEXT_PUBLIC_TRAIN_URL: process.env.NEXT_PUBLIC_TRAIN_URL || '',
          NEXT_PUBLIC_BOOKING_URL: process.env.NEXT_PUBLIC_BOOKING_URL || '',
          NEXT_PUBLIC_ADMIN_URL: process.env.NEXT_PUBLIC_ADMIN_URL || '',
        }} />
        {children}
      </body>
    </html>
  );
}
